services:
  db:
    image: mariadb:latest
    # Stockage des données persistantes
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    networks:
      - app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - app-network

  nginx:
    depends_on: 
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - wp_data:/var/www/html
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - app-network

volumes:
  db_data:
  wp_data:

networks:
  app-network:
    driver: bridge  