services:
  traefik:
    image: "traefik:v2.10.5"
    restart: "always"
    command:
      # A désactiver pour la mise en prod
      # - "--api.insecure=true" 
      - "--providers.docker=true"  # Voir pour peut-être désactiver pour la mise en prod et passer par l'API docker si plus sécurisé
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      # Port pour l'interface web de Traefik à désactiver pour la mise en prod
      # - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      wp1-net:
      wp2-net:

networks:
  wp1-net:
  wp2-net: