services:
  traefik:
    image: "traefik:v2.10.5"
    restart: "always"
    command:
      - "--api.insecure=true"  # A désactiver pour la mise en prod
      - "--providers.docker=true"
      - "--entrypoints.web-secure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Port pour l'interface web de Traefik à désactiver pour la mise en prod
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - "wp1-net"
      - "wp2-net"

  mariadb-1:
    image: "mariadb:11.1.3-jammy"
    restart: "always"
    container_name: "mariadb-1"
    volumes:
      - "db-data-1:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=somewordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
    networks:
      - "wp1-net"
    labels:
      - "traefik.enable=false"

  wordpress-1:
    depends_on: 
      - "mariadb-1"
    image: "wordpress:6.4.1"
    restart: "always"
    container_name: "wordpress-1"
    volumes:
      - "wp-data-1:/var/www/html/wordpress-1"
    environment:
      - "WORDPRESS_DB_HOST=mariadb-1"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "WORDPRESS_DB_NAME=wordpress"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-1.rule=Host(`site1.com`)"  # Faire l'enregistrement sur le fichier host de site1.com avec l'IP du host
      - "traefik.http.services.wordpress-1.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress-1.tls=true"
    networks:
      - "wp1-net"

  mariadb-2:
    image: "mariadb:11.1.3-jammy"
    restart: "always"
    container_name: "mariadb-2"
    volumes:
      - "db-data-2:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=somewordpress"
      - "MYSQL_DATABASE=wordpress"
      - "MYSQL_USER=wordpress"
      - "MYSQL_PASSWORD=wordpress"
    networks:
      - "wp2-net"
    labels:
      - "traefik.enable=false"

  wordpress-2:
    depends_on: 
      - "mariadb-2"
    image: "wordpress:6.4.1"
    restart: "always"
    container_name: "wordpress-2"
    volumes:
      - "wp-data-2:/var/www/html/wordpress-2"
    environment:
      - "WORDPRESS_DB_HOST=mariadb-2"
      - "WORDPRESS_DB_USER=wordpress"
      - "WORDPRESS_DB_PASSWORD=wordpress"
      - "WORDPRESS_DB_NAME=wordpress"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress-2.rule=Host(`site2.com`)"  # Faire l'enregistrement sur le fichier host de site1.com avec l'IP du host
      - "traefik.http.services.wordpress-2.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress-2.tls=true"
    networks:
      - "wp2-net"

volumes:
  db-data-1:
  wp-data-1:
  db-data-2:
  wp-data-2:

networks:
  wp1-net:
  wp2-net: