services:
  mariadb:
    image: mariadb:11.1.3-jammy
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress

  wordpress:
    depends_on: 
      - mariadb
    # image fpm nécessaire pour communication entre fastcgi wordpress et nginx
    image: wordpress:6.4.1-fpm-alpine
    container_name: wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress

  nginx:
    depends_on: 
      - wordpress
    image: nginx:1.25.3-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - wp_data:/var/www/html
      - ./nginx/:/etc/nginx/conf.d

volumes:
  db_data:
  wp_data: